//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CancionesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Canciones
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string Grupo { get; set; }
        public string Año { get; set; }
        public string Genero { get; set; }
    }
}
